<a href="https://colab.research.google.com/github/jundeyo/DFC605-16/blob/master/%EA%B3%A0%EB%A0%A4%EB%8C%80%EB%A1%9C%EA%B3%A0_%EB%8D%B0%EC%9D%B4%ED%84%B0%EC%A0%84%EC%B2%98%EB%A6%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 이미지 전처리 : 데이터셋만들기

**고려대학교 로고와 다른 혼재된 로고가 있는 원본파일과 고려대학교가 있는 로고만 있는것을 만든다.**

**또한 고려대학교 로고를 라벨링 한다.**

base : 고려대학교 로고
base-label : 고려대학교 로고 라벨
korea : 고려대학교 로고 스라이싱

샘플링 5개에서 15개로 변경함.




In [9]:
import os, re, glob
import cv2
import numpy as np
from sklearn.model_selection import train_test_split
from PIL import Image
from matplotlib import pyplot as plt
  
groups_folder_path = '/content/drive/My Drive/Colab Notebooks/'
categories = ["base","base-label","korea"]
 
num_classes = len(categories)

i = 0

for idex, categorie in enumerate(categories):
    label = [0 for i in range(num_classes)]
    label[idex] = 1
    image_dir = groups_folder_path + categorie + '/'
    arrtest = []
    for top, dir, f in os.walk(image_dir):
        dd = 1      
        for filename in f:

            print(image_dir+str(dd)+'.PNG')
            img = Image.open(image_dir+str(dd)+'.PNG')
            data = np.array(img, dtype='float32' )
            dd = dd + 1
            arrtest.append(data)
            print(data.shape)

    arrtest = np.expand_dims(arrtest, axis=0)
    arrtest.shape
    arrtest /= 255.

    arrtest = np.squeeze(arrtest, axis=0)
    #print(arrtest.shape)
    #print(arrtest)
    np.save(groups_folder_path + categorie + '.npy', arrtest)

imgs = np.load('/content/drive/My Drive/Colab Notebooks/base.npy', allow_pickle=True)

print(imgs.shape)
imgs = np.load('/content/drive/My Drive/Colab Notebooks/base-label.npy', allow_pickle=True)

print(imgs.shape)
imgs = np.load('/content/drive/My Drive/Colab Notebooks/korea.npy', allow_pickle=True)

print(imgs.shape)


/content/drive/My Drive/Colab Notebooks/base/1.PNG
(720, 1280, 3)
/content/drive/My Drive/Colab Notebooks/base/2.PNG
(720, 1280, 3)
/content/drive/My Drive/Colab Notebooks/base/3.PNG
(720, 1280, 3)
/content/drive/My Drive/Colab Notebooks/base/4.PNG
(720, 1280, 3)
/content/drive/My Drive/Colab Notebooks/base/5.PNG
(720, 1280, 3)
/content/drive/My Drive/Colab Notebooks/base/6.PNG
(720, 1280, 3)
/content/drive/My Drive/Colab Notebooks/base/7.PNG
(720, 1280, 3)
/content/drive/My Drive/Colab Notebooks/base/8.PNG
(720, 1280, 3)
/content/drive/My Drive/Colab Notebooks/base/9.PNG
(720, 1280, 3)
/content/drive/My Drive/Colab Notebooks/base/10.PNG
(720, 1280, 3)
/content/drive/My Drive/Colab Notebooks/base/11.PNG
(720, 1280, 3)
/content/drive/My Drive/Colab Notebooks/base/12.PNG
(720, 1280, 3)
/content/drive/My Drive/Colab Notebooks/base/13.PNG
(720, 1280, 3)
/content/drive/My Drive/Colab Notebooks/base/14.PNG
(720, 1280, 3)
/content/drive/My Drive/Colab Notebooks/base/15.PNG
(720, 1280, 3)
/con

**고려대학교 로고를 슬라이싱하여 라벨을 한다.**
샘플링 5개에서 15개로 변경함.

In [6]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

image = cv2.imread('/content/drive/My Drive/Colab Notebooks/korea-label/1.png',cv2.IMREAD_GRAYSCALE) / 255.
image1 = cv2.imread('/content/drive/My Drive/Colab Notebooks/korea-label/2.png',cv2.IMREAD_GRAYSCALE) / 255.
image2 = cv2.imread('/content/drive/My Drive/Colab Notebooks/korea-label/3.png',cv2.IMREAD_GRAYSCALE) / 255.
image3 = cv2.imread('/content/drive/My Drive/Colab Notebooks/korea-label/4.png',cv2.IMREAD_GRAYSCALE) / 255.
image4 = cv2.imread('/content/drive/My Drive/Colab Notebooks/korea-label/5.png',cv2.IMREAD_GRAYSCALE) / 255.

image5 = cv2.imread('/content/drive/My Drive/Colab Notebooks/korea-label/6.png',cv2.IMREAD_GRAYSCALE) / 255.
image6 = cv2.imread('/content/drive/My Drive/Colab Notebooks/korea-label/7.png',cv2.IMREAD_GRAYSCALE) / 255.
image7 = cv2.imread('/content/drive/My Drive/Colab Notebooks/korea-label/8.png',cv2.IMREAD_GRAYSCALE) / 255.
image8 = cv2.imread('/content/drive/My Drive/Colab Notebooks/korea-label/9.png',cv2.IMREAD_GRAYSCALE) / 255.
image9 = cv2.imread('/content/drive/My Drive/Colab Notebooks/korea-label/10.png',cv2.IMREAD_GRAYSCALE) / 255.
image10 = cv2.imread('/content/drive/My Drive/Colab Notebooks/korea-label/11.png',cv2.IMREAD_GRAYSCALE) / 255.
image11 = cv2.imread('/content/drive/My Drive/Colab Notebooks/korea-label/12.png',cv2.IMREAD_GRAYSCALE) / 255.
image12 = cv2.imread('/content/drive/My Drive/Colab Notebooks/korea-label/13.png',cv2.IMREAD_GRAYSCALE) / 255.
image13 = cv2.imread('/content/drive/My Drive/Colab Notebooks/korea-label/14.png',cv2.IMREAD_GRAYSCALE) / 255.
image14 = cv2.imread('/content/drive/My Drive/Colab Notebooks/korea-label/15.png',cv2.IMREAD_GRAYSCALE) / 255.

image25 = []
image25.append(image);
image25.append(image1);
image25.append(image2);
image25.append(image3);
image25.append(image4);
image25.append(image5);
image25.append(image6);
image25.append(image7);
image25.append(image8);
image25.append(image9);
image25.append(image10);
image25.append(image11);
image25.append(image12);
image25.append(image13);
image25.append(image14);

print(image5)
   
np.save('/content/drive/My Drive/Colab Notebooks/korea-label.npy', image25)

imgs = np.load('/content/drive/My Drive/Colab Notebooks/korea-label.npy', allow_pickle=True)

print(imgs.shape)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(15,)
