In [0]:
import os, re, glob
import cv2
import numpy as np
from sklearn.model_selection import train_test_split
from PIL import Image
from matplotlib import pyplot as plt

  
groups_folder_path = 'C:/dataset/'
categories = ["base","base-label","korea","korea-label"]
 
num_classes = len(categories)

i = 0


for idex, categorie in enumerate(categories):
    label = [0 for i in range(num_classes)]
    label[idex] = 1
    image_dir = groups_folder_path + categorie + '/'
    arrtest = []
    for top, dir, f in os.walk(image_dir):
        for filename in f:
            print(image_dir+filename)
            img = Image.open(image_dir+filename)
            data = np.array(img, dtype='float32' )
            arrtest.append(data)
            #print(arrtest)

    arrtest = np.expand_dims(arrtest, axis=0)
    arrtest.shape
    arrtest /= 255.

    arrtest = np.squeeze(arrtest, axis=0)
    #print(arrtest.shape)
    #print(arrtest)

    np.save(categorie + '.npy', arrtest)

#imgs = np.load('arrtest.npy', allow_pickle=True).astype(np.float32) / 255.
#print(imgs.shape)

In [22]:
from keras.preprocessing import image
import numpy as np
img = image.load_img("1.PNG", target_size=(1280, 780))
img_tensor = image.img_to_array(img)


img_tensor = np.expand_dims(img_tensor, axis=0)
img_tensor.shape
img_tensor /= 255.

np.save('test.npy', img_tensor)
print(img_tensor)
print(img_tensor.shape)

imgs = np.load('test.npy', allow_pickle=True).astype(np.float32) / 255.
print(imgs.shape)


[[[[0.972549   0.972549   0.972549  ]
   [0.972549   0.972549   0.972549  ]
   [0.9882353  0.99215686 0.99607843]
   ...
   [1.         1.         1.        ]
   [1.         1.         1.        ]
   [1.         1.         1.        ]]

  [[0.972549   0.972549   0.972549  ]
   [0.972549   0.972549   0.972549  ]
   [0.9882353  0.99215686 0.99607843]
   ...
   [1.         1.         1.        ]
   [1.         1.         1.        ]
   [1.         1.         1.        ]]

  [[0.972549   0.9764706  0.96862745]
   [0.98039216 0.98039216 0.9882353 ]
   [0.8901961  0.89411765 0.79607844]
   ...
   [1.         1.         1.        ]
   [1.         1.         1.        ]
   [1.         1.         1.        ]]

  ...

  [[0.26666668 0.44705883 0.76862746]
   [0.26666668 0.44705883 0.76862746]
   [0.26666668 0.44705883 0.76862746]
   ...
   [1.         1.         1.        ]
   [1.         1.         1.        ]
   [1.         1.         1.        ]]

  [[1.         1.         1.        ]
   [1. 

In [0]:
img_files = []
for root, dirs, files in os.walk("", topdown=False):
    for name in files:
        img_files.append(os.path.join(root, name))
img_files = sorted(img_files)

y_pred = []
y_test = []

for img_path in tqdm(img_files):
    # print(img_path)
    img = image.load_img(img_path, target_size=(224, 224))
    x = image.img_to_array(img)
    preds = model.predict(x[None, :, :, :])
    decoded = decode_predictions(preds, top=1)
    pred_label = decoded[0][0][0]
    # print(pred_label)
    y_pred.append(pred_label)
    tokens = img_path.split(os.pathsep)
    class_id = int(tokens[-2])
    # print(str(class_id))
    y_test.append(class_id)

return y_pred, y_test 

In [0]:
#img_array = np.load('test.npy')

#files.download('test.npy')